### ISSUE TITLE
能否在ModuleJarClassLoader load class设置白名单， 不与宿主环境隔离

### ISSUE THREAD

**Issue by 550932785** [alibaba/jvm-sandbox#398]
当前遇到一个问题  想通过sandbox动态的给宿主环境添加拦截器 
拦截器加载进去了 但是运行时会报异常 classnotfound   
该问题通过javassist解决
但是带来了另一个问题  宿主环境与sandbox环境需要通过在拦截器中使用context进行通信  
但是这个context 类不管由谁那个环境classloader加载都会有问题  只能交个更上层的appclassloader处理
由于sandbox的隔离机制 尽管交给appclassloader处理 但在sandbox中使用时依然会使用ModuleJarClassLoader加载的这个类
所有 想问有什么解决办法 或者开辟白名单的方式 解决环境隔离带来的问题

**Comment by oldmanpushcart** [comment]
在分支[develop-for-20220822](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20220822)中尝试通过在module的jar文件指定位置中约定一个yaml文件，来开放这个白名单，但一些代码还需要调整。

**Comment by oldmanpushcart** [comment]
在module的jar包中，约定了一个配置文件'META-INF/class-routing-config.yaml'，大概内容如下

```yaml
# 路由启用总开关: true - 打开 | false - 关闭
classRoutingEnable: true

# 路由配置读取方式:
# 方式一: yaml - 通过yaml方式配置，比较纯净轻量级方式，通过文件读取生成配置，不支持targetClassLoader模式
# 方式二: spi  - 通过SPI方式配置，支持targetClassLoader（指定classloader）路由，该方式会多一次模块jar的加载，有额外内存开销
routingConfigType: yaml

# yaml方式配置列表，配置参数如下:
# usingApp: 是否优先使用业务容器类加载器
# type: 路由匹配类型
# targetName: 匹配器目标类型
# pattern: 路由匹配表达式，{@link RoutingURLClassLoader$Routing }, 支持多个匹配表达式
routingConfigs:
 # dubbo 目标类名方式路由参考
 -
  usingApp: true
  type: 'targetClass'
  targetName: 'org.apache.dubbo.rpc.model.ApplicationModel'
  pattern: ['^org.apache.dubbo..*']

 # http 目标类名方式路由参考
 -
  usingApp: true
  type: 'targetClass'
  targetName: 'javax.servlet.http.HttpServlet'
  pattern: [ '^javax.servlet..*' ]

 # dubbo 目标类加载器模式路由参考
 -
  type: 'targetClassloaderName'
  targetName: 'org.apache.catalina.loader.WebappClassLoader'
  pattern: ['^org.apache.dubbo..*']
```

这个文件在module-jar被加载的过程中会被`com.alibaba.jvm.sandbox.core.classloader.SpecialRoutingHandler`所解析，并生成一个`List<RoutingInfo>`类加载和ClassLoader的映射条件集合，在真正类加载的时候通过这个集合进行判断应该使用哪一个ClassLoader完成类加载。

这个代码还有问题，还在REVIEW和重构。
